--------------------------------------------------------
--  파일이 생성됨 - 화요일-7월-23-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQ_BOARD_NUM
--------------------------------------------------------

   CREATE SEQUENCE  "PROJECTPSY"."SEQ_BOARD_NUM"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 46 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table DATABOARD
--------------------------------------------------------

  CREATE TABLE "PROJECTPSY"."DATABOARD" 
   (	"IDX" NUMBER, 
	"NAME" VARCHAR2(50 BYTE), 
	"TITLE" VARCHAR2(200 BYTE), 
	"CONTENT" VARCHAR2(2000 BYTE), 
	"POSTDATE" DATE DEFAULT sysdate, 
	"OFILE" VARCHAR2(200 BYTE), 
	"SFILE" VARCHAR2(30 BYTE), 
	"DOWNCOUNT" NUMBER(5,0) DEFAULT 0, 
	"PASS" VARCHAR2(50 BYTE), 
	"VISITCOUNT" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "PROJECTPSY"."MEMBER" 
   (	"ID" VARCHAR2(30 BYTE), 
	"PASS" VARCHAR2(10 BYTE), 
	"NAME" VARCHAR2(30 BYTE), 
	"PHONE" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into PROJECTPSY.DATABOARD
SET DEFINE OFF;
Insert into PROJECTPSY.DATABOARD (IDX,NAME,TITLE,CONTENT,POSTDATE,OFILE,SFILE,DOWNCOUNT,PASS,VISITCOUNT) values (6,'김유신','자료실 제목1 입니다.','내용',to_date('24/07/22','RR/MM/DD'),null,null,0,'1234',0);
Insert into PROJECTPSY.DATABOARD (IDX,NAME,TITLE,CONTENT,POSTDATE,OFILE,SFILE,DOWNCOUNT,PASS,VISITCOUNT) values (7,'장보고','자료실 제목2 입니다.','내용',to_date('24/07/22','RR/MM/DD'),null,null,0,'1234',0);
Insert into PROJECTPSY.DATABOARD (IDX,NAME,TITLE,CONTENT,POSTDATE,OFILE,SFILE,DOWNCOUNT,PASS,VISITCOUNT) values (8,'이순신','자료실 제목3 입니다.','내용',to_date('24/07/22','RR/MM/DD'),null,null,0,'1234',0);
Insert into PROJECTPSY.DATABOARD (IDX,NAME,TITLE,CONTENT,POSTDATE,OFILE,SFILE,DOWNCOUNT,PASS,VISITCOUNT) values (9,'강감찬','자료실 제목4 입니다.','내용',to_date('24/07/22','RR/MM/DD'),null,null,0,'1234',0);
Insert into PROJECTPSY.DATABOARD (IDX,NAME,TITLE,CONTENT,POSTDATE,OFILE,SFILE,DOWNCOUNT,PASS,VISITCOUNT) values (10,'대조영','자료실 제목5 입니다.','내용',to_date('24/07/22','RR/MM/DD'),null,null,0,'1234',0);
Insert into PROJECTPSY.DATABOARD (IDX,NAME,TITLE,CONTENT,POSTDATE,OFILE,SFILE,DOWNCOUNT,PASS,VISITCOUNT) values (11,'김유신','자료실 제목1 입니다.','내용',to_date('24/07/23','RR/MM/DD'),null,null,0,'1234',0);
Insert into PROJECTPSY.DATABOARD (IDX,NAME,TITLE,CONTENT,POSTDATE,OFILE,SFILE,DOWNCOUNT,PASS,VISITCOUNT) values (12,'장보고','자료실 제목2 입니다.','내용',to_date('24/07/23','RR/MM/DD'),null,null,0,'1234',0);
Insert into PROJECTPSY.DATABOARD (IDX,NAME,TITLE,CONTENT,POSTDATE,OFILE,SFILE,DOWNCOUNT,PASS,VISITCOUNT) values (13,'이순신','자료실 제목3 입니다.','내용',to_date('24/07/23','RR/MM/DD'),null,null,0,'1234',0);
Insert into PROJECTPSY.DATABOARD (IDX,NAME,TITLE,CONTENT,POSTDATE,OFILE,SFILE,DOWNCOUNT,PASS,VISITCOUNT) values (14,'강감찬','자료실 제목4 입니다.','내용',to_date('24/07/23','RR/MM/DD'),null,null,0,'1234',0);
Insert into PROJECTPSY.DATABOARD (IDX,NAME,TITLE,CONTENT,POSTDATE,OFILE,SFILE,DOWNCOUNT,PASS,VISITCOUNT) values (15,'대조영','자료실 제목5 입니다.','내용',to_date('24/07/23','RR/MM/DD'),null,null,0,'1234',0);
Insert into PROJECTPSY.DATABOARD (IDX,NAME,TITLE,CONTENT,POSTDATE,OFILE,SFILE,DOWNCOUNT,PASS,VISITCOUNT) values (16,'김유신','자료실 제목1 입니다.','내용',to_date('24/07/23','RR/MM/DD'),null,null,0,'1234',0);
Insert into PROJECTPSY.DATABOARD (IDX,NAME,TITLE,CONTENT,POSTDATE,OFILE,SFILE,DOWNCOUNT,PASS,VISITCOUNT) values (17,'장보고','자료실 제목2 입니다.','내용',to_date('24/07/23','RR/MM/DD'),null,null,0,'1234',0);
Insert into PROJECTPSY.DATABOARD (IDX,NAME,TITLE,CONTENT,POSTDATE,OFILE,SFILE,DOWNCOUNT,PASS,VISITCOUNT) values (18,'이순신','자료실 제목3 입니다.','내용',to_date('24/07/23','RR/MM/DD'),null,null,0,'1234',0);
Insert into PROJECTPSY.DATABOARD (IDX,NAME,TITLE,CONTENT,POSTDATE,OFILE,SFILE,DOWNCOUNT,PASS,VISITCOUNT) values (19,'강감찬','자료실 제목4 입니다.','내용',to_date('24/07/23','RR/MM/DD'),null,null,0,'1234',0);
Insert into PROJECTPSY.DATABOARD (IDX,NAME,TITLE,CONTENT,POSTDATE,OFILE,SFILE,DOWNCOUNT,PASS,VISITCOUNT) values (20,'대조영','자료실 제목5 입니다.','내용',to_date('24/07/23','RR/MM/DD'),null,null,0,'1234',0);
Insert into PROJECTPSY.DATABOARD (IDX,NAME,TITLE,CONTENT,POSTDATE,OFILE,SFILE,DOWNCOUNT,PASS,VISITCOUNT) values (21,'김유신','자료실 제목1 입니다.','내용',to_date('24/07/23','RR/MM/DD'),null,null,0,'1234',0);
Insert into PROJECTPSY.DATABOARD (IDX,NAME,TITLE,CONTENT,POSTDATE,OFILE,SFILE,DOWNCOUNT,PASS,VISITCOUNT) values (22,'장보고','자료실 제목2 입니다.','내용',to_date('24/07/23','RR/MM/DD'),null,null,0,'1234',0);
Insert into PROJECTPSY.DATABOARD (IDX,NAME,TITLE,CONTENT,POSTDATE,OFILE,SFILE,DOWNCOUNT,PASS,VISITCOUNT) values (23,'이순신','자료실 제목3 입니다.','내용',to_date('24/07/23','RR/MM/DD'),null,null,0,'1234',0);
Insert into PROJECTPSY.DATABOARD (IDX,NAME,TITLE,CONTENT,POSTDATE,OFILE,SFILE,DOWNCOUNT,PASS,VISITCOUNT) values (24,'강감찬','자료실 제목4 입니다.','내용',to_date('24/07/23','RR/MM/DD'),null,null,0,'1234',0);
Insert into PROJECTPSY.DATABOARD (IDX,NAME,TITLE,CONTENT,POSTDATE,OFILE,SFILE,DOWNCOUNT,PASS,VISITCOUNT) values (25,'대조영','자료실 제목5 입니다.','내용',to_date('24/07/23','RR/MM/DD'),null,null,0,'1234',0);
Insert into PROJECTPSY.DATABOARD (IDX,NAME,TITLE,CONTENT,POSTDATE,OFILE,SFILE,DOWNCOUNT,PASS,VISITCOUNT) values (26,'김유신','자료실 제목1 입니다.','내용',to_date('24/07/23','RR/MM/DD'),null,null,0,'1234',0);
Insert into PROJECTPSY.DATABOARD (IDX,NAME,TITLE,CONTENT,POSTDATE,OFILE,SFILE,DOWNCOUNT,PASS,VISITCOUNT) values (27,'장보고','자료실 제목2 입니다.','내용',to_date('24/07/23','RR/MM/DD'),null,null,0,'1234',0);
Insert into PROJECTPSY.DATABOARD (IDX,NAME,TITLE,CONTENT,POSTDATE,OFILE,SFILE,DOWNCOUNT,PASS,VISITCOUNT) values (28,'이순신','자료실 제목3 입니다.','내용',to_date('24/07/23','RR/MM/DD'),null,null,0,'1234',0);
Insert into PROJECTPSY.DATABOARD (IDX,NAME,TITLE,CONTENT,POSTDATE,OFILE,SFILE,DOWNCOUNT,PASS,VISITCOUNT) values (29,'강감찬','자료실 제목4 입니다.','내용',to_date('24/07/23','RR/MM/DD'),null,null,0,'1234',0);
Insert into PROJECTPSY.DATABOARD (IDX,NAME,TITLE,CONTENT,POSTDATE,OFILE,SFILE,DOWNCOUNT,PASS,VISITCOUNT) values (30,'대조영','자료실 제목5 입니다.','내용',to_date('24/07/23','RR/MM/DD'),null,null,0,'1234',0);
Insert into PROJECTPSY.DATABOARD (IDX,NAME,TITLE,CONTENT,POSTDATE,OFILE,SFILE,DOWNCOUNT,PASS,VISITCOUNT) values (31,'김유신','자료실 제목1 입니다.','내용',to_date('24/07/23','RR/MM/DD'),null,null,0,'1234',0);
Insert into PROJECTPSY.DATABOARD (IDX,NAME,TITLE,CONTENT,POSTDATE,OFILE,SFILE,DOWNCOUNT,PASS,VISITCOUNT) values (32,'장보고','자료실 제목2 입니다.','내용',to_date('24/07/23','RR/MM/DD'),null,null,0,'1234',0);
Insert into PROJECTPSY.DATABOARD (IDX,NAME,TITLE,CONTENT,POSTDATE,OFILE,SFILE,DOWNCOUNT,PASS,VISITCOUNT) values (33,'이순신','자료실 제목3 입니다.','내용',to_date('24/07/23','RR/MM/DD'),null,null,0,'1234',0);
Insert into PROJECTPSY.DATABOARD (IDX,NAME,TITLE,CONTENT,POSTDATE,OFILE,SFILE,DOWNCOUNT,PASS,VISITCOUNT) values (34,'강감찬','자료실 제목4 입니다.','내용',to_date('24/07/23','RR/MM/DD'),null,null,0,'1234',0);
Insert into PROJECTPSY.DATABOARD (IDX,NAME,TITLE,CONTENT,POSTDATE,OFILE,SFILE,DOWNCOUNT,PASS,VISITCOUNT) values (35,'대조영','자료실 제목5 입니다.','내용',to_date('24/07/23','RR/MM/DD'),null,null,0,'1234',0);
Insert into PROJECTPSY.DATABOARD (IDX,NAME,TITLE,CONTENT,POSTDATE,OFILE,SFILE,DOWNCOUNT,PASS,VISITCOUNT) values (36,'김유신','자료실 제목1 입니다.','내용',to_date('24/07/23','RR/MM/DD'),null,null,0,'1234',0);
Insert into PROJECTPSY.DATABOARD (IDX,NAME,TITLE,CONTENT,POSTDATE,OFILE,SFILE,DOWNCOUNT,PASS,VISITCOUNT) values (37,'장보고','자료실 제목2 입니다.','내용',to_date('24/07/23','RR/MM/DD'),null,null,0,'1234',0);
Insert into PROJECTPSY.DATABOARD (IDX,NAME,TITLE,CONTENT,POSTDATE,OFILE,SFILE,DOWNCOUNT,PASS,VISITCOUNT) values (38,'이순신','자료실 제목3 입니다.','내용',to_date('24/07/23','RR/MM/DD'),null,null,0,'1234',0);
Insert into PROJECTPSY.DATABOARD (IDX,NAME,TITLE,CONTENT,POSTDATE,OFILE,SFILE,DOWNCOUNT,PASS,VISITCOUNT) values (39,'강감찬','자료실 제목4 입니다.','내용',to_date('24/07/23','RR/MM/DD'),null,null,0,'1234',0);
Insert into PROJECTPSY.DATABOARD (IDX,NAME,TITLE,CONTENT,POSTDATE,OFILE,SFILE,DOWNCOUNT,PASS,VISITCOUNT) values (40,'대조영','자료실 제목5 입니다.','내용',to_date('24/07/23','RR/MM/DD'),null,null,0,'1234',0);
Insert into PROJECTPSY.DATABOARD (IDX,NAME,TITLE,CONTENT,POSTDATE,OFILE,SFILE,DOWNCOUNT,PASS,VISITCOUNT) values (41,'김유신','자료실 제목1 입니다.','내용',to_date('24/07/23','RR/MM/DD'),null,null,0,'1234',30);
Insert into PROJECTPSY.DATABOARD (IDX,NAME,TITLE,CONTENT,POSTDATE,OFILE,SFILE,DOWNCOUNT,PASS,VISITCOUNT) values (42,'장보고','자료실 제목2 입니다.','내용',to_date('24/07/23','RR/MM/DD'),null,null,0,'1234',1);
Insert into PROJECTPSY.DATABOARD (IDX,NAME,TITLE,CONTENT,POSTDATE,OFILE,SFILE,DOWNCOUNT,PASS,VISITCOUNT) values (43,'이순신','자료실 제목3 입니다.','내용',to_date('24/07/23','RR/MM/DD'),null,null,0,'1234',1);
Insert into PROJECTPSY.DATABOARD (IDX,NAME,TITLE,CONTENT,POSTDATE,OFILE,SFILE,DOWNCOUNT,PASS,VISITCOUNT) values (44,'강감찬','자료실 제목4 입니다.','내용',to_date('24/07/23','RR/MM/DD'),null,null,0,'1234',2);
Insert into PROJECTPSY.DATABOARD (IDX,NAME,TITLE,CONTENT,POSTDATE,OFILE,SFILE,DOWNCOUNT,PASS,VISITCOUNT) values (45,'대조영','자료실 제목5 입니다.','내용',to_date('24/07/23','RR/MM/DD'),null,null,0,'1234',9);
REM INSERTING into PROJECTPSY.MEMBER
SET DEFINE OFF;
Insert into PROJECTPSY.MEMBER (ID,PASS,NAME,PHONE,EMAIL) values ('aaaa','a','a','a','a@naver.com');
Insert into PROJECTPSY.MEMBER (ID,PASS,NAME,PHONE,EMAIL) values ('b','b','b','b','b@naver.com');
Insert into PROJECTPSY.MEMBER (ID,PASS,NAME,PHONE,EMAIL) values ('sunny2','a','a','a','a@naver.com');
Insert into PROJECTPSY.MEMBER (ID,PASS,NAME,PHONE,EMAIL) values ('test1','1234','테스트1회원','0103335555','abc@naver.com');
Insert into PROJECTPSY.MEMBER (ID,PASS,NAME,PHONE,EMAIL) values ('stu543','1234','새멤버','01098765432','a@naver.com');
Insert into PROJECTPSY.MEMBER (ID,PASS,NAME,PHONE,EMAIL) values ('suuny','1234',' sunny','01098765432','a@naver.com');
Insert into PROJECTPSY.MEMBER (ID,PASS,NAME,PHONE,EMAIL) values ('newmember','1234','새멤버','01098765432','psy6951@gmail.com');
Insert into PROJECTPSY.MEMBER (ID,PASS,NAME,PHONE,EMAIL) values ('newmember2','1234','새멤버','01098765432','a@naver.com');
Insert into PROJECTPSY.MEMBER (ID,PASS,NAME,PHONE,EMAIL) values ('newmember3','1234','새멤버','01098765432','psy6951@gmail.com');
Insert into PROJECTPSY.MEMBER (ID,PASS,NAME,PHONE,EMAIL) values ('newmember4','1234','새멤버4','01098765432','psy6951@gmail.com');
Insert into PROJECTPSY.MEMBER (ID,PASS,NAME,PHONE,EMAIL) values ('newmember5','1234','새멤버5','01098765432','psy6951@gmail.com');
Insert into PROJECTPSY.MEMBER (ID,PASS,NAME,PHONE,EMAIL) values ('newmember6','1234','PARK','01035996951','stu543@naver.com');
Insert into PROJECTPSY.MEMBER (ID,PASS,NAME,PHONE,EMAIL) values ('sunny','1234','박선영','01012345678','psy6951@gmail.com');
Insert into PROJECTPSY.MEMBER (ID,PASS,NAME,PHONE,EMAIL) values ('1stmember','1234','첫번째회원','01012345678','psy6951@gmail.com');
Insert into PROJECTPSY.MEMBER (ID,PASS,NAME,PHONE,EMAIL) values ('3rdmember','1234','세번째회원','01012345678','psy6951@gmail.com');
Insert into PROJECTPSY.MEMBER (ID,PASS,NAME,PHONE,EMAIL) values ('4thmember','1234','네번째회원','01012345678','psy6951@gmail.com');
Insert into PROJECTPSY.MEMBER (ID,PASS,NAME,PHONE,EMAIL) values ('5thmember','1234','다섯번째회원','01012345678','psy6951@gmail.com');
Insert into PROJECTPSY.MEMBER (ID,PASS,NAME,PHONE,EMAIL) values ('d','d','d','d','ddddd@naver.com');
Insert into PROJECTPSY.MEMBER (ID,PASS,NAME,PHONE,EMAIL) values ('11','11','11','11','11@11');
Insert into PROJECTPSY.MEMBER (ID,PASS,NAME,PHONE,EMAIL) values ('sunny000','12345','박선영','01012345678','a@naver.com');
--------------------------------------------------------
--  DDL for Index SYS_C008422
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECTPSY"."SYS_C008422" ON "PROJECTPSY"."MEMBER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008451
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECTPSY"."SYS_C008451" ON "PROJECTPSY"."DATABOARD" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008451
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECTPSY"."SYS_C008451" ON "PROJECTPSY"."DATABOARD" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008422
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECTPSY"."SYS_C008422" ON "PROJECTPSY"."MEMBER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table DATABOARD
--------------------------------------------------------

  ALTER TABLE "PROJECTPSY"."DATABOARD" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "PROJECTPSY"."DATABOARD" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "PROJECTPSY"."DATABOARD" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "PROJECTPSY"."DATABOARD" MODIFY ("POSTDATE" NOT NULL ENABLE);
  ALTER TABLE "PROJECTPSY"."DATABOARD" MODIFY ("DOWNCOUNT" NOT NULL ENABLE);
  ALTER TABLE "PROJECTPSY"."DATABOARD" MODIFY ("PASS" NOT NULL ENABLE);
  ALTER TABLE "PROJECTPSY"."DATABOARD" MODIFY ("VISITCOUNT" NOT NULL ENABLE);
  ALTER TABLE "PROJECTPSY"."DATABOARD" ADD PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "PROJECTPSY"."MEMBER" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PROJECTPSY"."MEMBER" MODIFY ("PASS" NOT NULL ENABLE);
  ALTER TABLE "PROJECTPSY"."MEMBER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "PROJECTPSY"."MEMBER" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE "PROJECTPSY"."MEMBER" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "PROJECTPSY"."MEMBER" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
